### ISSUE TITLE
List of things to fix in the code

### ISSUE THREAD

**Issue by Alberth289346** [CorsixTH/CorsixTH#1372]
Issue for tracking found issues, so they aren't forgotten

- [ ] th_gfx.cpp, `_setmin` (or now `set_left_to_min`), replace by `std::min` #1370 
- [ ] th_gfx.h, `set_speed` uses a comma as statement separator. #1370

**Comment by lewri** [comment]
@Alberth289346 are the two of th_gfx now resolved by #1370?

**Comment by Alberth289346** [comment]
No, both still exist.

@TheCycoONE can probably easier point out things that still need to be fixed in the cpp code.

**Comment by ARGAMX** [comment]
Maybe we can create a separate task for each item in this list with a more detailed descriptions and a meaningful names?
Currently this issue seems like some kind of incomprehensible, strange, non-atomic issue. 🙂
May be this issue can be converted to a [META] issue?

**Comment by lewri** [comment]
At the least separate issues by file or scope (like the list in the OP). This may be picked up by those interested using better defining scopes. It's likely we have indeed noted them down, but then got forgotten about.

The first `other` I'm not sure of where it wants to precisely target as an issue; needs an example.

**Comment by Alberth289346** [comment]
`set_left_to_min`:
```
th_gfx.cpp
304:void set_left_to_min(int& iLeft, int iRight) {
341:    set_left_to_min(oFrame.bounding_left, oElement.x);
342:    set_left_to_min(oFrame.bounding_top, oElement.y);
```
It assigns the result to the left parameter, in-place. Depending on what is done around lines 341 and 342, that may be easy to fix.

`set_speed`:
```
th_gfx.h
586:  void set_speed(int iX, int iY) { speed.dx = iX, speed.dy = iY; }
626:  void set_speed(int iX, int iY) { dx_per_tick = iX, dy_per_tick = iY; }
```
Very trivial to fix.

`string_list` (and `linklist` too) uses C-style lists, where a list element contains both the value and the list-administration (to the next/previous element). Making it a proper `vector<...>` or so thus needs to split code that handles such a list into more separate  notions "element value" and "the list".  
Don't know about `string_list` but for `linklist` it's non-trivial.

Streaming code I'd have to check more closely. I am not sure currently how reading and writing functions relate to each other.  
If it is within reading sprite data from original data files, the bigger issue there is that it's OO-programming in C. I fixed that in a Java implementation, and a similar approach could be done in C++. That needs however very careful refactoring.  
I should still have the result somewhere.

----
The first two issues are useful for starting C++ programmers, but aren't terribly interesting. The others need more knowledge and experience with both C-style and Cpp-style programming.

I am fine with closing this issue.
